"""
Renders the per-route divergence.csv of each condition as Markdown tables (one table per condition).

Run divergence.py first. Columns use only the metrics that are valid for TF++'s ~10 m path:
lateral and speed error at the 0.5 s horizon (1 s / 2 s run past the end of the planned path).
Friction re-applies come from <condition>/<seed>/simulation_results_friction.jsonl.

Usage:
  python friction_ood/analysis/summary_tables.py results/pilot/tfpp --out results/pilot/tfpp/summary_tables.md
"""
import argparse
import csv
import glob
import json
import os

# Braking calibration (friction_ood/calibration/outputs/summary.csv): tire friction scale -> mu_eff = a / g.
MU_EFF = {1.0: 0.76, 0.3: 0.52, 0.1: 0.28, 0.05: 0.14, 0.02: 0.06}

COLUMNS = ['Route', 'Scenario', 'Status', 'DS', 'RC', 'Infractions', 'Lat err 0.5 s (m)', 'Speed err 0.5 s (m/s)',
           'Peak sideslip (°)', 'Yaw-rate RMSE (rad/s)', 'Friction re-applies']


def load_reapplies(cond_dir):
  path = os.path.join(cond_dir, 'simulation_results_friction.jsonl')
  if not os.path.exists(path):
    return {}
  with open(path, encoding='utf-8') as f:
    return {d['route']: len(d.get('reapply_ticks', [])) for d in map(json.loads, f)}


def format_infractions(raw):
  # Bench2Drive no longer counts min-speed infractions in the driving score, so leave them out.
  inf = {k: v for k, v in json.loads(raw).items() if k != 'min_speed_infractions'}
  label = lambda k: k.replace('collisions_', '') + ' collision' if k.startswith('collisions_') else k
  return ', '.join(f'{label(k).replace("_", " ")} ×{v}' for k, v in inf.items()) or '—'


def condition_table(cond_dir, title):
  with open(os.path.join(cond_dir, 'divergence.csv'), encoding='utf-8') as f:
    rows = sorted(csv.DictReader(f), key=lambda r: int(r['route'].split('_')[1]))
  reapplies = load_reapplies(cond_dir)

  lines = [f'### {title}', '', '| ' + ' | '.join(COLUMNS) + ' |', '|' + '---|' * len(COLUMNS)]
  for r in rows:
    lines.append('| ' + ' | '.join([
        r['route'].split('_')[1],
        r['scenario'].rsplit('_', 1)[0],
        r['status'].replace('Failed - ', 'Failed: '),
        f"{float(r['driving_score']):.1f}",
        f"{float(r['route_completion']):.0f}",
        format_infractions(r['infractions']),
        f"{float(r['lat_err_0.5s_mean']):.2f}",
        f"{float(r['speed_err_0.5s_mean']):+.2f}",
        f"{float(r['peak_sideslip_deg']):.1f}",
        f"{float(r['yaw_rate_rmse']):.2f}",
        str(reapplies.get(r['route'], '—')),
    ]) + ' |')

  mean = lambda k: sum(float(r[k]) for r in rows) / len(rows)
  completed = sum(r['status'] == 'Completed' for r in rows)
  lines.append('| ' + ' | '.join([
      '**Mean**', '', f'{completed}/{len(rows)} completed', f"**{mean('driving_score'):.1f}**",
      f"**{mean('route_completion'):.1f}**", f"{mean('collisions'):.1f} collisions/route",
      f"**{mean('lat_err_0.5s_mean'):.2f}**", f"**{mean('speed_err_0.5s_mean'):+.2f}**",
      f"**{mean('peak_sideslip_deg'):.1f}**", f"**{mean('yaw_rate_rmse'):.2f}**", ''
  ]) + ' |')
  return '\n'.join(lines)


def main():
  parser = argparse.ArgumentParser()
  parser.add_argument('model_dir', help='e.g. results/pilot/tfpp (contains <mode>_mu<scale>/<seed>/divergence.csv)')
  parser.add_argument('--seed', default='seed0')
  parser.add_argument('--out', default=None, help='Markdown file to write (default: <model_dir>/summary_tables.md)')
  args = parser.parse_args()

  # Folders starting with '_' hold superseded / invalid runs and are skipped.
  conds = sorted(glob.glob(os.path.join(args.model_dir, '[!_]*', args.seed, 'divergence.csv')),
                 key=lambda p: -float(p.split('_mu')[1].split(os.sep)[0]))  # dry (largest scale) first
  sections = [f'# {os.path.basename(os.path.normpath(args.model_dir))}: per-route results ({args.seed})', '',
              'Generated by `friction_ood/analysis/summary_tables.py` from each condition\'s `divergence.csv`.', '',
              '- **DS / RC**: Bench2Drive driving score / route completion (%).',
              '- **Infractions**: min-speed infractions are omitted (not counted in the B2D driving score).',
              '- **Lat err 0.5 s**: distance of the car 0.5 s later from the path it planned (m). 1 s / 2 s are '
              'omitted: they run past the end of TF++\'s ~10 m path.',
              '- **Speed err 0.5 s**: actual speed 0.5 s later minus the chosen target speed (m/s); negative = slower.',
              '- **Peak sideslip**: max |atan(v_lat / v_long)| while moving > 2 m/s.',
              '- **Yaw-rate RMSE**: actual yaw rate vs. the TF++ kinematic bicycle model (dry-road reference).',
              '- **Friction re-applies**: times the enforcer restored the target tire friction after CARLA reset it.', '']
  for path in conds:
    cond_dir = os.path.dirname(path)
    cond = os.path.basename(os.path.dirname(cond_dir))
    scale = float(cond.split('_mu')[1])
    label = f' (μ_eff ≈ {MU_EFF[scale]:.2f})' if scale in MU_EFF else ''
    sections += [condition_table(cond_dir, f'{cond}: tire friction scale {scale}{label}'), '']

  out = args.out or os.path.join(args.model_dir, 'summary_tables.md')
  with open(out, 'w', encoding='utf-8') as f:
    f.write('\n'.join(sections))
  print(f'wrote {out}')


if __name__ == '__main__':
  main()
